### PR TITLE
Using conference 'config' data as new Conference-Doc if it exists

### PR DESCRIPTION
**Pull request by dhuynh-Kazoo**
Updated: Under-testing
---
**Detail with example in 3rd comment**

Currently, when we add `config` fields to conference callflow, it does not reflect the changes because the predefined conference doc overwrite that (https://github.com/2600hz/kazoo-conference/blob/7e7ff3bce12335aba18a7a7d4cfbc7dfd1019135/src/conf_discovery_req.erl#L53). 

A way to fix that is getting `Conference-Doc` from DiscoveryReq, then merge the Conference Doc to  `Conference-Doc` object, so any changes will be applied

### CODE REVIEW

**Comment by lazedo** [comment]
@dhuynh-Kazoo not sure what you're trying to fix here,  this is already done in kapps_conference:from_json

**Comment by dhuynh-Kazoo** [comment]
hi @lazedo, it is under testing and review again, I will share the details later

**Comment by dhuynh-Kazoo** [comment]
Hi @lazedo, adding my findings. Please correct me if I'm wrong. My new code that merging does not work (no voice when calling to conference) so I am checking again.

-----
I have a conference call flow(I am using kazoo pivot format) with this config: play sound when entering and exiting.

```
{
    "module": "conference",
    "data": {
        "id": "5c11e0de657dc78082fedec7f2fd7f70",
        "config": {
            "name": "Dat Test Conf ID with Config Object",
            "play_entry_tone": true,
            "play_exit_tone": true
        }
        
    }
}
````
play_entry_tone and play_exit_tone will be added to <<"Conference-Doc">> of DiscoveryReq.

I have set up the do not play sound for both `entry and exit` actions from monster-ui for this conference, so the conference doc has these fields:
```
            "play_entry_tone": false,
            "play_exit_tone": false
```

Because we set Conference Doc from Db to `<<"Conference-Doc">>` of `DiscoveryReq` https://github.com/2600hz/kazoo-conference/blob/7e7ff3bce12335aba18a7a7d4cfbc7dfd1019135/src/conf_discovery_req.erl#L53. So the changes we want never be applied because it is overwritten.

What we got in WithConferenceDoc is 
```
                        {<<"play_entry_tone">>,false},
                        {<<"play_exit_tone">>,false},
```

That should be both true because we added in config field

```
                        {<<"play_entry_tone">>,true},
                        {<<"play_exit_tone">>,true},
```

**Comment by lazedo** [comment]
afaicr you shouldn't mix `id` with `config` in the callflow 
```
          ,{<<"Conference-ID">>, kz_doc:id(Data)}
          ,{<<"Moderator">>, kz_json:get_binary_boolean(<<"moderator">>, Data)}
          ,{<<"Play-Welcome">>, kz_json:is_true([<<"welcome_prompt">>, <<"play">>], Data, 'true')}
          ,{<<"Play-Welcome-Media">>, kz_json:get_ne_value([<<"welcome_prompt">>, <<"media_id">>], Data)}
          ,{<<"Conference-Doc">>, kz_json:get_json_value(<<"config">>, Data)}
          ,{<<"Play-Exit-Tone">>, kz_json:get_ne_value([<<"play_exit_tone">>], Data)}
          ,{<<"Play-Entry-Tone">>, kz_json:get_ne_value([<<"play_entry_tone">>], Data)}
```

how would you then use
`,{<<"Play-Exit-Tone">>, kz_json:get_ne_value([<<"play_exit_tone">>], Data)}` ?

**Comment by dhuynh-Kazoo** [comment]
I set no sound for entering and existing actions from monster-ui, then I tried this but did not hear any sound. 
```
{
    "module": "conference",
    "data": {
        "id": "5c11e0de657dc78082fedec7f2fd7f70",
        "play_entry_tone": true,
        "play_exit_tone": true
    }
}
```
Following the ad-hoc example (https://github.com/2600hz/kazoo-pivot/blob/master/doc/kazoo/conferencing.md#ad-hoc-example) so I thought I should put them inside the `config` 

Do you know the differences between putting `play_entry_tone` inside `config` and outside of `config`?

**Comment by dhuynh-Kazoo** [comment]
Closed the PR as for TwiML we provide 2 types:

- Conference ID -> using static conference, not allow to change any config from pivot
- Conference Name -> using the ad-hod conference, so can apply any config from pivot

**Pull request closed without merging**
